services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=1
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
