services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dcat
      POSTGRES_USER: dcat
      POSTGRES_PASSWORD: dcatpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U dcat -d dcat"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media:/app/media
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_DB_ENGINE=postgres
      - DJANGO_DB_NAME=dcat
      - DJANGO_DB_USER=dcat
      - DJANGO_DB_PASSWORD=dcatpass
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_ALLOWED_HOSTS=172.23.98.169,localhost,127.0.0.1
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata:
  media:
